apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-repo
data:
  branch: main
  host: github.com
  protocol: https
  repo: https://github.com/cloud-native-garage-method-cohort/kuldeeps-ci-cd-pubrepo
  org: cloud-native-garage-method-cohort
  parentdir: bash -c 'echo qa/$(basename ${NAMESPACE} -dev)'
